<?php 
/**
 * Implements hook_help().
 *
 * Displays help and module information.
 */
function isp_module_help($path, $arg) {
  switch ($path) {
    case "admin/help#isp_module":
      return t("Shows ssl certificates list"); 
      break; 
  }
}

/**
 * Implements hook_menu().
 */
function isp_module_menu() {
  $items = array();

  $items['admin/config/development/isp_module'] = array(
    'title' => 'ISP SSL list',
    'description' => 'Configuration for ISP module. SSL list.',
    'page callback' => 'isp_module_page_content',
    'access arguments' => array('access administration page'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback: ISP module settings
 */
/**
 * Simple page content.
 */
function isp_module_page_content() {
  $base = drupal_get_path('module', 'isp_module');
  $css_path = $base .'/isp_module.css';
  $js_path = $base .'/isp_module.js';
  drupal_add_css($css_path);
  drupal_add_js($js_path);

  $output = '<section class="ssl-cert">';
  $output .= '<div class="ssl-cert__list">';
  $output .= '</div></section>';


  return $output;
}
?>